services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-v11-boilerplate-app # suffix used since container names must be unique(see postgres and redis container names below)
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    volumes:
      - ./public/uploads:/app/public/uploads # persist uploaded files
    depends_on:
      postgres:
        condition: service_healthy # wait for postgres to be ready
      redis:
        condition: service_healthy # wait for redis to be ready
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: nest-v11-boilerplate-postgres
    ports:
      - "5432:5432"
    environment:
      # POSTGRES_USER: postgres
      POSTGRES_USER: ${POSTGRES_USER:-postgres}           # reads from .env.docker. Uses default value
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}           # reads from .env.docker. Uses default value
      POSTGRES_DB: ${POSTGRES_DB:-nest-v11-boilerplate}   # reads from .env.docker. Uses default value
      POSTGRES_HOST_AUTH_METHOD: trust                    # required for blank password
    volumes:
      - postgres_data:/var/lib/postgresql/data # persist database data
    healthcheck:  # postgres health check
      test: ["CMD-SHELL", "pg_isready -U postgres"] 
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: nest-v11-boilerplate-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data # persist redis data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: