// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config' // works outside docker
import { defineConfig, env } from 'prisma/config'

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'ts-node --project tsconfig.json -r tsconfig-paths/register prisma/seed.ts' // NOTE: seeder path. For docker only
    // seed: 'tsx prisma/seed.ts' // NOTE: seeder path. For local only
  },
  datasource: {
    url: env('DATABASE_URL')
  }
})
